title: Msc Cyber Security Portfolio
author: Diogo Neno
subtitle:
markdown: kramdown
exclude:
  - README.txt
  - LICENSE.txt

# Contact details
email: diogoneno@proton.me
linkedin_url: https://www.linkedin.com/in/diogoamarantes/
github_url: https://github.com/diogoneno
